### ISSUE TITLE
Homey reports thunderstorms, Yahoo reports mostly cloudy.

### ISSUE THREAD

**Issue by magind** [athombv/com.yahoo.weather#5]
The weather at my location right now is cloudy according to Yahoo. I can confirm this by looking out the window. However, the Homey reports thunderstorms when I ask it for a weather report. There is no thunderstorms reported at any weather service in the near future or past. 
Homey has reported thunderstorms earlier too with the weather being overcast or similar.
App version: 1.1.0. Homey firmware: 1.3.1.

**Comment by RobinBol** [comment]
There is indeed sometimes a difference between what the Yahoo website says, and what the API reports, I am afraid this is not something we can fix.

**Comment by magind** [comment]
Ah, didn't realize the API was the problem. Closing the issue then. 
Thank you for a quick reply!
